---
title: "36-315 Lab 09, Spring 2018"
author: "Anthony Chan(alc1), Minwhan cho(minwhanc), Zhichuan Duan(zhichuad), Devansh Kukreja(dkukreja)"
date: "Due Friday, April 6, 2018 (6:30pm) on Canvas"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  show
---


##  Lab 09:  Static Graphics Group Project


#  Instructions

###  This week, you will work in groups to submit the assignment.

###  Each group should designate one group member to submit the assignment on Canvas.

###  The assignment should include all group members' names.


***
***


#  Problem 1

(10 points)

***Assignment**:  Get to know your group members.*

***What you have to turn in**:  Write at least one sentence about each group member that's in attendance today.  This could be their hometown, their major(s)/minor(s), their favorite foods/restaurants, their favorite movies/TV shows, or anything else that's appropriate.*

***
***

#  Problem 2

(20 points)

***Assignment**:  Read the Static Graphics Group Project file on Canvas.*

*Then sign up at [the link here](https://docs.google.com/spreadsheets/d/1y63NVm0R6NbUKmHmHTO_l0_EdOgVf4KYWgZedYAirEQ/edit?usp=sharing) for a meeting with one of Jerzy, Nic, or Matteo on Tuesday 4/10, to get feedback on your **complete** poster draft. At least one group member **must** attend---this counts for one-third of your poster-project grade! Of course, we encourage the whole group to come.*

*Jerzy has 15-minute time slots available during 10am to 5pm in BH 140D (Mac computer lab). Matteo/Nic have 15-minute time slots available during 1:30pm to 3:30pm in BH 132Q (Statistics department, ground floor).*

***What you have to turn in**:  Fill in below:*

* Our team has signed up on the spreadsheet for poster review on Tuesday April 10 at _____[time slot]_____ in room _____[room number]_____.
* Team members _____[names]_____ will attend the poster review on April 10 and communicate feedback to the rest of the team.

***
***


#  Problem 3

(40 points)

***Assignment**:  Choose your dataset for the Static Graphics Group Project.  Dataset suggestions, resources, and requirements are provided in the Static Graphics Group Project file on Canvas.*

**What you have to turn in**:  


https://archive.ics.uci.edu/ml/datasets/Online+Retail#
541,909 rows and 8 columns.  Each observation corresponds to a particular item on a purchase. The invoice number is the purchase ID, the stock code is the item number, the description is a basic overview of the product, the quantity is the number of the itmes purchased, the invoice date is the date of the purchase, the unit price is the price of the item, the customerId is the unique identifier of each customer, and the country is the identifier for each country.


***
***



#  Problem 4

(20 points)

***Assignment**:  Brainstorm at least three questions you'd like to answer with your dataset.*

***What you have to turn in**:  At least three ideas of questions you can anwer with your dataset, and how you might answer them graphically.  This may include specific ideas about the types of graphs you'll create, or simply sentences like "What is the relationship between the age of shark attack victims and the year in which the shark attack occured?  Does this change depending on the gender of the victim?"*



***
***


#  Problem 5

(2 points each)

*Look up the help documentation for the following functions:  `pdf()`, `png()`, and `ggsave()`.*

*(a)  What other functions are listed in the help file for `png()`?*

*(b)  How do you control the height and width of images with the `pdf()` function?  What are the units for these parameters?*

*(c)  How do you control the height and width of images with the `png()` function?  What are the **default** units for these parameters?*

*(d)  What types of images can you save with the `ggsave()` function?  (Hint:  Look at the `device` parameter.)*

*(e)  What does the `dpi` parameter control in the `ggsave()` function?  What does `dpi` stand for?*


***Note**: these functions will be very useful for you as you prepare your posters, especially `pdf()` and `ggsave()`.  Note that these functions are called when you click "Export" in the Plot window in RStudio.*

*PNG images typically will appear more pixelated when printed on a large, 3' x 4' poster.  PDF images typically will scale to any size much better. (If you have 1000s of data points on a graph, PNG images will render on your computer much faster than PDFs, but this is not as important when the graphic is meant to be printed on a poster.)*

*When adding graphs that you saved to your poster, **do not stretch them** after including them in your poster.  If you want to change their dimensions, do this by adjusting the parameters in the functions above and re-generating the graphs.*

***
***



#  That was easy.  What do we do next?

(a)  Start working on the graphs for your poster!  See the Static Graphics Group Project file for more information. Choose a poster template as well (from Canvas or elsewhere).

(b)  Schedule some times when you are all available to meet over the next few days to work on the project.

(c)  Decide how you want to share code (e.g. with GitHub?) or other resources for the project.  


###  Using GitHub

Note:  If you're familiar with GitHub already, that's great!  But remember that not everyone knows how to use this incredibly useful tool.  Share this knowledge with your group members!  Help teach them how to set it up and use it!

Note:  You are not required to use GitHub to share code for the project.  Do whatever your group is most comfortable with.

For those interested, here are some resources that help to explain how to use GitHub with RStudio:

+  [Jenny Bryan's Tutorial](https://jennybc.github.io/2014-05-12-ubc/ubc-r/session03_git.html)
+  [RStudio's Support Page](https://support.rstudio.com/hc/en-us/articles/200532077-Version-Control-with-Git-and-SVN)
+  [R Bloggers](https://www.r-bloggers.com/rstudio-and-github/)
+  [Molecular Ecologist Blog](http://www.molecularecologist.com/2013/11/using-github-with-r-and-rstudio/)


